library(datasets)
attach(airquality)
mean(Ozone)
is.na(airquality)
is.na(Ozone)
sum(is.na(Ozone))
sum(is.na(airquality))
mean(Ozone, na.rm = TRUE)
airquality_without_missing=na.omit(airquality)
dim(airquality_without_missing)
dim(airquality)
missing_ind = complete.cases(Ozone)
missing_ind
d = which((is.na(airquality)), arr.ind = TRUE)
dim(d)